# Generated by Django 6.0.1 on 2026-01-21 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(choices=[("EX", "Expense"), ("IN", "Income")]),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Rent", "Rent"),
                            ("Transportation", "Transportation"),
                            ("Utilities", "Utilities"),
                            ("Food", "Food"),
                            ("Healthcare", "Healthcare"),
                            ("Entertainment", "Entertainment"),
                            ("Other", "Other"),
                            ("Salary", "Salary"),
                            ("Gift", "Gift"),
                        ]
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
