# Generated by Django 6.0.1 on 2026-01-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="income",
            options={"ordering": ["date"]},
        ),
    ]
